### PR TITLE
Proposal to delete one inbox.

### PR DESCRIPTION
**Pull request by marcandreuf**
Hello, this is my proposal to allow to delete inboxes created by mistake or not wanted anymore.

I hope it helps.

### CODE REVIEW

**Comment by leafac** [comment]
Hi @marcandreuf,

Thanks for the pull request. It’s clear and straightforward code and I appreciate how you included tests.

That said, I’m not 100% sure we should merge this. Typically what people do when they want to stop using an inbox is just unsubscribe from the newsletter with the publisher and unsubscribe from the feed, effectively abandoning the Kill the Newsletter! inbox. That probably means that there are some ghost inboxes in the database, but I think that’s okay.

If we were to include this feature, I think we’d also need to present it to the users in a different way. Maybe have a form on the homepage where you’d copy your inbox email address or feed address and it would delete the inbox for you.

What do you think?

**Comment by rhythms06** [comment]
Not sure how feasible this is, but another way to go about it could be to include a link to delete the inbox in the "Inbox created" article that gets added to each feed. That way the website UI stays clean, and users always have a way to delete the inbox via their feed.

**Comment by leafac** [comment]
I think that @rhythms06’s idea is even better than mine—it’s much more ergonomic and resembles the “unsubscribe” links that newsletters typically include on the footer. Let’s just make that the users is presented with a “confirm inbox deletion” button before actually deleting the inbox, to prevent issues with people clicking on the link by accident.

But, above all, do y’all think it’s better to have all this instead of just letting inboxes be abandoned?

**Comment by rhythms06** [comment]
Thank you @leafac! That's a great point about it being familiar UX. And I agree about having a confirmation button. 

> But, above all, do y’all think it’s better to have all this instead of just letting inboxes be abandoned?

I think some small fraction of users will enjoy the feature, and in that way it's worth it; it's the sort of feature that makes the product feel more cohesive, but isn't actually totally necessary. I wouldn't prioritize it over other features or spend a ton of time on it.

**Comment by leafac** [comment]
@marcandreuf & @rhythms06 Can y’all work together to modify the pull request and introduce the changes we discussed? First, introduce the “delete inbox” link at the bottom of each Atom feed entry. Second, have some sort of confirmation before the inbox is actually deleted.

**Comment by rhythms06** [comment]
Totally! I'll take a look this week.

**Comment by leafac** [comment]
I implemented this idea and it’ll be out on the next release of Kill the Newsletter!

Thanks for the conversation.

**Comment by rhythms06** [comment]
Amazing, thanks @leafac! My sincere apologies for abandoning this thread, it's wonderful seeing you pick it up and keep improving KtN. Happy to be of help down the line :)

**Pull request closed without merging**
